Fix test failures in JAX under NumPy 1.25.0rc1.
`jnp.finfo(...)` of an Array type yields:

```
TypeError: unhashable type: 'ArrayImpl'
```

However, `np.finfo(...)` no longer accepts NumPy arrays as input either, so it would be consistent to require the user to pass a dtype where they are currently passing an array.

PiperOrigin-RevId: 538516573